// Code generated by pigeon; DO NOT EDIT.

package bvh

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"
)

type Hierarchy struct {
	Root   Joint
	Motion Motion
}

type Joint struct {
	Id       string
	Offset   [3]float64
	Channels []Channel
	Joints   []Joint
	EndSite  [3]float64
}

type Channel string

const Xposition = Channel("Xposition")
const Yposition = Channel("Yposition")
const Zposition = Channel("Zposition")
const Xrotation = Channel("Xrotation")
const Yrotation = Channel("Yrotation")
const Zrotation = Channel("Zrotation")

type Motion struct {
	FrameTime time.Duration
	Frames    []Frame
}

type Frame []float64

var g = &grammar{
	rules: []*rule{
		{
			name: "program",
			pos:  position{line: 51, col: 1, offset: 943},
			expr: &actionExpr{
				pos: position{line: 51, col: 12, offset: 954},
				run: (*parser).callonprogram1,
				expr: &seqExpr{
					pos: position{line: 51, col: 12, offset: 954},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 51, col: 12, offset: 954},
							val:        "hierarchy",
							ignoreCase: true,
							want:       "\"HIERARCHY\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 51, col: 25, offset: 967},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 51, col: 27, offset: 969},
							label: "root",
							expr: &ruleRefExpr{
								pos:  position{line: 51, col: 32, offset: 974},
								name: "root",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 51, col: 37, offset: 979},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 51, col: 39, offset: 981},
							label: "motion",
							expr: &ruleRefExpr{
								pos:  position{line: 51, col: 46, offset: 988},
								name: "motion",
							},
						},
					},
				},
			},
		},
		{
			name: "root",
			pos:  position{line: 55, col: 1, offset: 1069},
			expr: &actionExpr{
				pos: position{line: 55, col: 9, offset: 1077},
				run: (*parser).callonroot1,
				expr: &seqExpr{
					pos: position{line: 55, col: 9, offset: 1077},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 55, col: 9, offset: 1077},
							val:        "root",
							ignoreCase: true,
							want:       "\"ROOT\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 55, col: 17, offset: 1085},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 55, col: 19, offset: 1087},
							label: "id",
							expr: &ruleRefExpr{
								pos:  position{line: 55, col: 22, offset: 1090},
								name: "id",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 55, col: 25, offset: 1093},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 55, col: 27, offset: 1095},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 55, col: 31, offset: 1099},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 55, col: 33, offset: 1101},
							label: "offset",
							expr: &ruleRefExpr{
								pos:  position{line: 55, col: 40, offset: 1108},
								name: "offset",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 55, col: 47, offset: 1115},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 55, col: 49, offset: 1117},
							label: "channels",
							expr: &ruleRefExpr{
								pos:  position{line: 55, col: 58, offset: 1126},
								name: "channels",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 55, col: 67, offset: 1135},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 55, col: 69, offset: 1137},
							label: "joints",
							expr: &zeroOrMoreExpr{
								pos: position{line: 55, col: 76, offset: 1144},
								expr: &ruleRefExpr{
									pos:  position{line: 55, col: 76, offset: 1144},
									name: "joint",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 55, col: 83, offset: 1151},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "joint",
			pos:  position{line: 63, col: 1, offset: 1400},
			expr: &choiceExpr{
				pos: position{line: 63, col: 10, offset: 1409},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 63, col: 10, offset: 1409},
						run: (*parser).callonjoint2,
						expr: &seqExpr{
							pos: position{line: 63, col: 10, offset: 1409},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 63, col: 10, offset: 1409},
									val:        "joint",
									ignoreCase: true,
									want:       "\"JOINT\"i",
								},
								&ruleRefExpr{
									pos:  position{line: 63, col: 19, offset: 1418},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 63, col: 21, offset: 1420},
									label: "id",
									expr: &ruleRefExpr{
										pos:  position{line: 63, col: 24, offset: 1423},
										name: "id",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 63, col: 27, offset: 1426},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 63, col: 29, offset: 1428},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&ruleRefExpr{
									pos:  position{line: 63, col: 33, offset: 1432},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 63, col: 35, offset: 1434},
									label: "offset",
									expr: &ruleRefExpr{
										pos:  position{line: 63, col: 42, offset: 1441},
										name: "offset",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 63, col: 49, offset: 1448},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 63, col: 51, offset: 1450},
									label: "channels",
									expr: &ruleRefExpr{
										pos:  position{line: 63, col: 60, offset: 1459},
										name: "channels",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 63, col: 69, offset: 1468},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 63, col: 71, offset: 1470},
									label: "joints",
									expr: &zeroOrMoreExpr{
										pos: position{line: 63, col: 78, offset: 1477},
										expr: &ruleRefExpr{
											pos:  position{line: 63, col: 78, offset: 1477},
											name: "joint",
										},
									},
								},
								&litMatcher{
									pos:        position{line: 63, col: 85, offset: 1484},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
								&ruleRefExpr{
									pos:  position{line: 63, col: 89, offset: 1488},
									name: "_",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 70, col: 11, offset: 1792},
						run: (*parser).callonjoint22,
						expr: &seqExpr{
							pos: position{line: 70, col: 11, offset: 1792},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 70, col: 11, offset: 1792},
									val:        "end site",
									ignoreCase: true,
									want:       "\"END SITE\"i",
								},
								&ruleRefExpr{
									pos:  position{line: 70, col: 23, offset: 1804},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 70, col: 25, offset: 1806},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&ruleRefExpr{
									pos:  position{line: 70, col: 29, offset: 1810},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 70, col: 31, offset: 1812},
									label: "offset",
									expr: &ruleRefExpr{
										pos:  position{line: 70, col: 38, offset: 1819},
										name: "offset",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 70, col: 45, offset: 1826},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 70, col: 47, offset: 1828},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
								&ruleRefExpr{
									pos:  position{line: 70, col: 51, offset: 1832},
									name: "_",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "offset",
			pos:  position{line: 74, col: 1, offset: 1921},
			expr: &actionExpr{
				pos: position{line: 74, col: 11, offset: 1931},
				run: (*parser).callonoffset1,
				expr: &seqExpr{
					pos: position{line: 74, col: 11, offset: 1931},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 74, col: 11, offset: 1931},
							val:        "offset",
							ignoreCase: true,
							want:       "\"OFFSET\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 74, col: 21, offset: 1941},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 74, col: 23, offset: 1943},
							label: "x",
							expr: &ruleRefExpr{
								pos:  position{line: 74, col: 25, offset: 1945},
								name: "float",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 74, col: 31, offset: 1951},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 74, col: 33, offset: 1953},
							label: "y",
							expr: &ruleRefExpr{
								pos:  position{line: 74, col: 35, offset: 1955},
								name: "float",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 74, col: 41, offset: 1961},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 74, col: 43, offset: 1963},
							label: "z",
							expr: &ruleRefExpr{
								pos:  position{line: 74, col: 45, offset: 1965},
								name: "float",
							},
						},
					},
				},
			},
		},
		{
			name: "channels",
			pos:  position{line: 78, col: 1, offset: 2042},
			expr: &actionExpr{
				pos: position{line: 78, col: 13, offset: 2054},
				run: (*parser).callonchannels1,
				expr: &seqExpr{
					pos: position{line: 78, col: 13, offset: 2054},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 78, col: 13, offset: 2054},
							val:        "channels",
							ignoreCase: true,
							want:       "\"CHANNELS\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 78, col: 25, offset: 2066},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 78, col: 27, offset: 2068},
							label: "count",
							expr: &charClassMatcher{
								pos:        position{line: 78, col: 33, offset: 2074},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&ruleRefExpr{
							pos:  position{line: 78, col: 39, offset: 2080},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 78, col: 41, offset: 2082},
							label: "channels",
							expr: &zeroOrMoreExpr{
								pos: position{line: 78, col: 50, offset: 2091},
								expr: &ruleRefExpr{
									pos:  position{line: 78, col: 50, offset: 2091},
									name: "channel_type",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "channel_type",
			pos:  position{line: 86, col: 1, offset: 2277},
			expr: &actionExpr{
				pos: position{line: 86, col: 17, offset: 2293},
				run: (*parser).callonchannel_type1,
				expr: &seqExpr{
					pos: position{line: 86, col: 17, offset: 2293},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 86, col: 17, offset: 2293},
							label: "channel_type",
							expr: &choiceExpr{
								pos: position{line: 87, col: 5, offset: 2313},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 87, col: 5, offset: 2313},
										val:        "xposition",
										ignoreCase: true,
										want:       "\"Xposition\"i",
									},
									&litMatcher{
										pos:        position{line: 88, col: 5, offset: 2332},
										val:        "yposition",
										ignoreCase: true,
										want:       "\"Yposition\"i",
									},
									&litMatcher{
										pos:        position{line: 89, col: 5, offset: 2351},
										val:        "zposition",
										ignoreCase: true,
										want:       "\"Zposition\"i",
									},
									&litMatcher{
										pos:        position{line: 90, col: 5, offset: 2370},
										val:        "xrotation",
										ignoreCase: true,
										want:       "\"Xrotation\"i",
									},
									&litMatcher{
										pos:        position{line: 91, col: 5, offset: 2389},
										val:        "yrotation",
										ignoreCase: true,
										want:       "\"Yrotation\"i",
									},
									&litMatcher{
										pos:        position{line: 92, col: 5, offset: 2408},
										val:        "zrotation",
										ignoreCase: true,
										want:       "\"Zrotation\"i",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 93, col: 3, offset: 2423},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "motion",
			pos:  position{line: 97, col: 1, offset: 2462},
			expr: &actionExpr{
				pos: position{line: 97, col: 11, offset: 2472},
				run: (*parser).callonmotion1,
				expr: &seqExpr{
					pos: position{line: 97, col: 11, offset: 2472},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 97, col: 11, offset: 2472},
							val:        "motion",
							ignoreCase: true,
							want:       "\"MOTION\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 97, col: 21, offset: 2482},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 97, col: 23, offset: 2484},
							val:        "frames:",
							ignoreCase: true,
							want:       "\"Frames:\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 97, col: 34, offset: 2495},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 97, col: 36, offset: 2497},
							label: "frameCount",
							expr: &ruleRefExpr{
								pos:  position{line: 97, col: 47, offset: 2508},
								name: "integer",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 97, col: 55, offset: 2516},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 97, col: 57, offset: 2518},
							val:        "frame time:",
							ignoreCase: true,
							want:       "\"Frame Time:\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 97, col: 72, offset: 2533},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 97, col: 74, offset: 2535},
							label: "frameTime",
							expr: &ruleRefExpr{
								pos:  position{line: 97, col: 84, offset: 2545},
								name: "float",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 97, col: 90, offset: 2551},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 97, col: 92, offset: 2553},
							label: "frames",
							expr: &zeroOrMoreExpr{
								pos: position{line: 97, col: 99, offset: 2560},
								expr: &ruleRefExpr{
									pos:  position{line: 97, col: 99, offset: 2560},
									name: "frame_data",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "frame_data",
			pos:  position{line: 105, col: 1, offset: 2814},
			expr: &actionExpr{
				pos: position{line: 105, col: 15, offset: 2828},
				run: (*parser).callonframe_data1,
				expr: &seqExpr{
					pos: position{line: 105, col: 15, offset: 2828},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 105, col: 15, offset: 2828},
							label: "frameValues",
							expr: &oneOrMoreExpr{
								pos: position{line: 105, col: 27, offset: 2840},
								expr: &ruleRefExpr{
									pos:  position{line: 105, col: 27, offset: 2840},
									name: "frame_value",
								},
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 105, col: 40, offset: 2853},
							expr: &charClassMatcher{
								pos:        position{line: 105, col: 40, offset: 2853},
								val:        "[\\n\\r]",
								chars:      []rune{'\n', '\r'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "frame_value",
			pos:  position{line: 113, col: 1, offset: 3025},
			expr: &actionExpr{
				pos: position{line: 113, col: 16, offset: 3040},
				run: (*parser).callonframe_value1,
				expr: &seqExpr{
					pos: position{line: 113, col: 16, offset: 3040},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 113, col: 16, offset: 3040},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 113, col: 22, offset: 3046},
								name: "float",
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 113, col: 28, offset: 3052},
							expr: &charClassMatcher{
								pos:        position{line: 113, col: 28, offset: 3052},
								val:        "[ ]",
								chars:      []rune{' '},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "id",
			pos:  position{line: 117, col: 1, offset: 3084},
			expr: &actionExpr{
				pos: position{line: 117, col: 7, offset: 3090},
				run: (*parser).callonid1,
				expr: &oneOrMoreExpr{
					pos: position{line: 117, col: 7, offset: 3090},
					expr: &charClassMatcher{
						pos:        position{line: 117, col: 7, offset: 3090},
						val:        "[a-zA-Z0-9-_]",
						chars:      []rune{'-', '_'},
						ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "float",
			pos:  position{line: 121, col: 1, offset: 3141},
			expr: &actionExpr{
				pos: position{line: 121, col: 10, offset: 3150},
				run: (*parser).callonfloat1,
				expr: &labeledExpr{
					pos:   position{line: 121, col: 10, offset: 3150},
					label: "value",
					expr: &oneOrMoreExpr{
						pos: position{line: 121, col: 16, offset: 3156},
						expr: &charClassMatcher{
							pos:        position{line: 121, col: 16, offset: 3156},
							val:        "[-0-9.eE]",
							chars:      []rune{'-', '.', 'e', 'E'},
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "integer",
			pos:  position{line: 125, col: 1, offset: 3222},
			expr: &actionExpr{
				pos: position{line: 125, col: 12, offset: 3233},
				run: (*parser).calloninteger1,
				expr: &oneOrMoreExpr{
					pos: position{line: 125, col: 12, offset: 3233},
					expr: &charClassMatcher{
						pos:        position{line: 125, col: 12, offset: 3233},
						val:        "[-0-9eE]",
						chars:      []rune{'-', 'e', 'E'},
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 129, col: 1, offset: 3300},
			expr: &actionExpr{
				pos: position{line: 129, col: 6, offset: 3305},
				run: (*parser).callon_1,
				expr: &zeroOrMoreExpr{
					pos: position{line: 129, col: 7, offset: 3306},
					expr: &charClassMatcher{
						pos:        position{line: 129, col: 7, offset: 3306},
						val:        "[ \\t\\n\\r]",
						chars:      []rune{' ', '\t', '\n', '\r'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
	},
}

func (c *current) onprogram1(root, motion any) (any, error) {
	return Hierarchy{Root: root.(Joint), Motion: motion.(Motion)}, nil
}

func (p *parser) callonprogram1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onprogram1(stack["root"], stack["motion"])
}

func (c *current) onroot1(id, offset, channels, joints any) (any, error) {
	jts := make([]Joint, len(joints.([]any)))
	for i := range joints.([]any) {
		jts[i] = joints.([]any)[i].(Joint)
	}
	return Joint{Id: id.(string), Offset: offset.([3]float64), Channels: channels.([]Channel), Joints: jts}, nil
}

func (p *parser) callonroot1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onroot1(stack["id"], stack["offset"], stack["channels"], stack["joints"])
}

func (c *current) onjoint2(id, offset, channels, joints any) (any, error) {
	jts := make([]Joint, len(joints.([]any)))
	for i := range joints.([]any) {
		jts[i] = joints.([]any)[i].(Joint)
	}
	return Joint{Id: id.(string), Offset: offset.([3]float64), Channels: channels.([]Channel), Joints: jts}, nil

}

func (p *parser) callonjoint2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onjoint2(stack["id"], stack["offset"], stack["channels"], stack["joints"])
}

func (c *current) onjoint22(offset any) (any, error) {
	return Joint{Id: "END SITE", EndSite: offset.([3]float64)}, nil

}

func (p *parser) callonjoint22() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onjoint22(stack["offset"])
}

func (c *current) onoffset1(x, y, z any) (any, error) {
	return [3]float64{x.(float64), y.(float64), z.(float64)}, nil
}

func (p *parser) callonoffset1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onoffset1(stack["x"], stack["y"], stack["z"])
}

func (c *current) onchannels1(count, channels any) (any, error) {
	chans := make([]Channel, len(channels.([]any)))
	for i := range channels.([]any) {
		chans[i] = channels.([]any)[i].(Channel)
	}
	return chans, nil
}

func (p *parser) callonchannels1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onchannels1(stack["count"], stack["channels"])
}

func (c *current) onchannel_type1(channel_type any) (any, error) {
	return Channel(c.text), nil
}

func (p *parser) callonchannel_type1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onchannel_type1(stack["channel_type"])
}

func (c *current) onmotion1(frameCount, frameTime, frames any) (any, error) {
	frms := make([]Frame, frameCount.(int64))
	for i := range frames.([]any) {
		frms[i] = frames.([]any)[i].(Frame)
	}
	return Motion{FrameTime: time.Duration(frameTime.(float64) * float64(time.Second)), Frames: frms}, nil
}

func (p *parser) callonmotion1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onmotion1(stack["frameCount"], stack["frameTime"], stack["frames"])
}

func (c *current) onframe_data1(frameValues any) (any, error) {
	vals := make(Frame, len(frameValues.([]any)))
	for i := range len(vals) {
		vals[i] = frameValues.([]any)[i].(float64)
	}
	return vals, nil
}

func (p *parser) callonframe_data1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onframe_data1(stack["frameValues"])
}

func (c *current) onframe_value1(value any) (any, error) {
	return value, nil
}

func (p *parser) callonframe_value1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onframe_value1(stack["value"])
}

func (c *current) onid1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonid1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onid1()
}

func (c *current) onfloat1(value any) (any, error) {
	return strconv.ParseFloat(string(c.text), 64)
}

func (p *parser) callonfloat1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onfloat1(stack["value"])
}

func (c *current) oninteger1() (any, error) {
	return strconv.ParseInt(string(c.text), 10, 64)
}

func (p *parser) calloninteger1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.oninteger1()
}

func (c *current) on_1() (any, error) {
	return nil, nil
}

func (p *parser) callon_1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.on_1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	var (
		val any
		ok  bool
	)

	val, ok = p.parseRule(rule)

	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	val, ok := p.parseExpr(expr)

	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}

		val = actVal
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	pt := p.pt
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			return val, ok
		}
	}
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	pt := p.pt
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
